######################################################################
##
## Filename: chords.udo
## Created on: Thu Nov 30 12:21:07 PM PST 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
