######################################################################
##
## Filename: chords_tb.udo
## Created on: Tue Nov 28 11:42:43 AM PST 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
