######################################################################
##
## Filename: dynamics_controller_tb.udo
## Created on: Sun Dec 03 11:47:25 AM PST 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
