######################################################################
##
## Filename: echo_tb.udo
## Created on: Sat Dec 02 02:40:26 PM PST 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
