######################################################################
##
## Filename: note_player_tb.udo
## Created on: Fri Dec 01 10:55:00 AM PST 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
