######################################################################
##
## Filename: song_reader_tb.udo
## Created on: Fri Dec 01 10:57:20 AM PST 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
