######################################################################
##
## Filename: wave_capture_tb.udo
## Created on: Fri Dec 01 10:53:24 AM PST 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
